defaults: 
  - base
  - _self_

dataset: ???              # {FunGraph3D | SceneFun3Ddev | SceneFun3Dtest | PADO}
scene_id: ???
save_folder_name: capa1   # set number to distinguish different runs
tagger: ram               # {ram | none}
detector: vlp             # {gdino | yolo | vlp}
use_part_knowledge: !!bool True
use_color_feat: !!bool True

# color feature extraction parameters. LAB + {Color Name + OPP + ... }
color_feat_params:
  bins: 32
  use_wb: true        # white balancing
  use_retinex: false
  s_threshold: 0.10
  v_spec_threshold: 0.90
  compute_cn: true      # Color Name
  compute_opp: true     # OPP
  compute_rg: false     # regulized RGB
  compute_med: false    # median
  clip_ab: 110.0

# gdino
gdino:
  box_threshold: 0.25
  text_threshold: 0.25
  nms_threshold: 0.5
  part_box_threshold: 0.15
  part_text_threshold: 0.15
  part_nms_threshold: 0.5

# yolo
yolo:
  box_threshold: 0.25
  text_threshold: 0.25
  nms_threshold: 0.5

# vlp
vlp:
  score_threshold: 0.3
  nms_threshold: 0.5
  part_nms_threshold: 0.5

# defaults
start: 0
end: -1
stride: 1

desired_height: 480
desired_width: 640

add_bg_classes: !!bool True
accumu_classes: !!bool True

skip_bg: !!bool False
bg_classes: [ "wall", "floor", "ceiling" ]

device: cuda
