defaults: 
  - base
  - _self_

tagger: ram           # {ram | none}
detector: vlp         # {gdino | yolo | vlp}
exp_suffix: v1
save_folder_name: capa
dataset: ???         # {FunGraph3D | SceneFun3Ddev | SceneFun3Dtest | PADO}
scene_id: ???

# gdino
gdino:
  box_threshold: 0.25
  text_threshold: 0.25
  nms_threshold: 0.5
  part_box_threshold: 0.15
  part_text_threshold: 0.15
  part_nms_threshold: 0.5

# yolo
yolo:
  box_threshold: 0.25
  text_threshold: 0.25
  nms_threshold: 0.5

# vlp
vlp:
  score_threshold: 0.3
  nms_threshold: 0.5
  part_nms_threshold: 0.5

# defaults
start: 0
end: -1
stride: 1

desired_height: 480
desired_width: 640

add_bg_classes: true
accumu_classes: true

skip_bg: false
bg_classes: [ "wall", "floor", "ceiling" ]

device: cuda
