defaults:
  - base
  - base_mapping
  - classes
  - logging_level
  - _self_
  # - replica
  - fungraph3d
  # - scenefun3d
  # - PADO

# ====================== Detection Model Setting ===================== #
# For object/part detection
# YOLO  : similar to concpeptgraph (YOLO-world + SAM + CLIP)
# GDINO : similar to openfungraph (RAM++ + GroundingDINO + SAM)
# CAPA: CAPA-3DSG (RAM + VLPart)
detector_mode: "CAPA" 
use_sam: !!bool False
render_multiview: !!bool True

# in YOLO mode or GDINO mode
sam_encoder: "vit_h"
box_thresh: 0.20
text_thresh: 0.20

# in CAPA
score_thresh: 0.30

texture_weight: 0.30        # visual과 섞는 비율
color_ema_alpha: 0.30       # 객체 색 모델 EMA
color_ab_rg_cn_weights: [0.50, 0.20, 0.20, 0.10]
color_sim_mapping: "inv"    # 또는 "exp"
color_sim_gamma: 3.0
color_use_wb: true
color_use_retinex: false
color_bins: 32
color_s_threshold: 0.10
color_v_spec_threshold: 0.90
color_compute_cn: true


out_dir: ""      # "" (Default: ./output/[exp_suffix]) or specify your path
max_frames: 10    # 0 for all frames, or specify a positive integer for max frames to process

object_part_knowledge: "${repo_root}/object_part_knowledge.json"
classes_output_filename: "merged_classes.txt"

# ====================== VLP Setting ===================== #
vlpart_ckpt_path: "${repo_root}/checkpoints/swinbase_cascade_lvis_paco.pth"
vlpart_cfg_path: "${repo_root}/src/thirdparty/vlpart/configs/joint/swinbase_cascade_lvis_paco.yaml"

# ====================== Detection Setting ===================== #
stride: 1
detections_exp_suffix: s_detections_stride${stride} # helpful label to identify your detections
exp_suffix: r_mapping_stride${stride} # helpful label to identify your mapping experiment
force_detection: !!bool True
save_detections: !!bool True
make_edges: !!bool True

# ====================== DENOSING Setting ===================== #
NMS_on: True
NMS_iou_thresh: 0.50

denoise_interval: 5           # default 5 # Run DBSCAN every k frame. This operation is heavy
filter_interval: 5            # default 5 # Filter objects that have too few associations or are too small
merge_interval: 5             # default 5 # Merge objects based on geometric and semantic similarity
run_denoise_final_frame: !!bool True
run_filter_final_frame: !!bool True
run_merge_final_frame: !!bool True

downsample_voxel_size: 0.01    # default 0.01
obj_pcd_max_points: 5000
obj_pcd_max_points_obj: 5000
obj_pcd_max_points_part: -1

dbscan_remove_noise: !!bool True
dbscan_eps: 0.1          # default 0.1
dbscan_min_points: 10     # default 10  

# Selection criteria of the fused object point cloud
obj_min_points: 50      # default 50
obj_min_detections: 2   # default 2 

# ====================== SAVE Setting ===================== #
use_rerun: !!bool False
save_rerun: !!bool False
save_video: !!bool True
debug_render: !!bool False
vis_render: !!bool False
save_objects_all_frames: !!bool False

multiview_color_mode: rgb